name: gradio
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - gradio
    - gradio_pdf
    - PyMuPDF
    - langchain
    - transformers
    - sentence-transformers
    - datasets
    - accelerate
    - faiss-cpu
    - torch
    - torchaudio
    - requests
    - python-dotenv
    - librosa
    - soundfile
