name: gradio
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - gradio
    - gradio_pdf
    - PyMuPDF
    - langchain
    - transformers
    - sentence-transformers
    - faiss-cpu
    - torch
    - requests
    - accelerator
    - python-dotenv
